#!/usr/bin/env python3
# postBuild for Qiber3D
# install K3D and patch vedo

import subprocess
import sys
from pathlib import Path


def run(*args, **kwargs):
    # Run a command, echoing the args; fails hard if something goes wrong
    print("\t", " ".join(args))
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)


print("Prepare K3D:")
run('jupyter', 'labextension', 'install', '@jupyter-widgets/jupyterlab-manager', cwd='/tmp')
run('jupyter', 'nbextension', 'enable', '--py', '--sys-prefix', 'k3d', cwd='/tmp')
run('jupyter', 'nbextension', 'install', '--py', '--sys-prefix', 'k3d', cwd='/tmp')
run('jupyter', 'nbextension', 'enable', '--py', '--sys-prefix', 'appmode', cwd='/tmp')
run('jupyter', 'serverextension', 'enable', '--py', '--sys-prefix', 'appmode', cwd='/tmp')

print("Patching vedo to enable color in k3d backend again")
to_patch = Path('/srv/conda/envs/notebook/lib/python3.7/site-packages/vedo/backends.py')
content = to_patch.read_text()
content = content.replace('# color=_rgb2int(iap.GetColor()),', 'color=_rgb2int(iap.GetColor()),')
to_patch.write_text(content)

print("Preparations done!")